export const LIST_EMOJI: Record<string, string> = {
  countries: "🌍",
  continents: "🌐",
  "national-parks": "🏞️",
  "us-states": "🗺️",
  "mlb-stadiums": "⚾",
  "nfl-stadiums": "🏈",
  "nba-arenas": "🏀",
  "nhl-arenas": "🏒",
  "new-7-wonders": "🏛️",
  "world-marathon-majors": "🏃",
  "grand-slam-tennis": "🎾",
  "f1-circuits": "🏎️",
  "studio-ghibli-films": "🐉",
  "pixar-films": "💡",
};
