-- 193 UN member states, alphabetical (with Ivory Coast between Italy and
-- Jamaica), plus the Holy See and Palestine appended at the end (194, 195)
-- since they are UN observer states rather than members.
-- code = ISO 3166-1 alpha-2.
with target_list as (
  select id from public.lists where slug = 'countries'
)
insert into public.list_items (list_id, name, code, sort_order)
select target_list.id, v.name, v.code, v.sort_order
from target_list, (values
  ('Afghanistan', 'AF', 1),
  ('Albania', 'AL', 2),
  ('Algeria', 'DZ', 3),
  ('Andorra', 'AD', 4),
  ('Angola', 'AO', 5),
  ('Antigua and Barbuda', 'AG', 6),
  ('Argentina', 'AR', 7),
  ('Armenia', 'AM', 8),
  ('Australia', 'AU', 9),
  ('Austria', 'AT', 10),
  ('Azerbaijan', 'AZ', 11),
  ('Bahamas', 'BS', 12),
  ('Bahrain', 'BH', 13),
  ('Bangladesh', 'BD', 14),
  ('Barbados', 'BB', 15),
  ('Belarus', 'BY', 16),
  ('Belgium', 'BE', 17),
  ('Belize', 'BZ', 18),
  ('Benin', 'BJ', 19),
  ('Bhutan', 'BT', 20),
  ('Bolivia', 'BO', 21),
  ('Bosnia and Herzegovina', 'BA', 22),
  ('Botswana', 'BW', 23),
  ('Brazil', 'BR', 24),
  ('Brunei', 'BN', 25),
  ('Bulgaria', 'BG', 26),
  ('Burkina Faso', 'BF', 27),
  ('Burundi', 'BI', 28),
  ('Cabo Verde', 'CV', 29),
  ('Cambodia', 'KH', 30),
  ('Cameroon', 'CM', 31),
  ('Canada', 'CA', 32),
  ('Central African Republic', 'CF', 33),
  ('Chad', 'TD', 34),
  ('Chile', 'CL', 35),
  ('China', 'CN', 36),
  ('Colombia', 'CO', 37),
  ('Comoros', 'KM', 38),
  ('Congo, Democratic Republic of the', 'CD', 39),
  ('Congo, Republic of the', 'CG', 40),
  ('Costa Rica', 'CR', 41),
  ('Croatia', 'HR', 42),
  ('Cuba', 'CU', 43),
  ('Cyprus', 'CY', 44),
  ('Czechia', 'CZ', 45),
  ('Denmark', 'DK', 46),
  ('Djibouti', 'DJ', 47),
  ('Dominica', 'DM', 48),
  ('Dominican Republic', 'DO', 49),
  ('Ecuador', 'EC', 50),
  ('Egypt', 'EG', 51),
  ('El Salvador', 'SV', 52),
  ('Equatorial Guinea', 'GQ', 53),
  ('Eritrea', 'ER', 54),
  ('Estonia', 'EE', 55),
  ('Eswatini', 'SZ', 56),
  ('Ethiopia', 'ET', 57),
  ('Fiji', 'FJ', 58),
  ('Finland', 'FI', 59),
  ('France', 'FR', 60),
  ('Gabon', 'GA', 61),
  ('Gambia', 'GM', 62),
  ('Georgia', 'GE', 63),
  ('Germany', 'DE', 64),
  ('Ghana', 'GH', 65),
  ('Greece', 'GR', 66),
  ('Grenada', 'GD', 67),
  ('Guatemala', 'GT', 68),
  ('Guinea', 'GN', 69),
  ('Guinea-Bissau', 'GW', 70),
  ('Guyana', 'GY', 71),
  ('Haiti', 'HT', 72),
  ('Honduras', 'HN', 73),
  ('Hungary', 'HU', 74),
  ('Iceland', 'IS', 75),
  ('India', 'IN', 76),
  ('Indonesia', 'ID', 77),
  ('Iran', 'IR', 78),
  ('Iraq', 'IQ', 79),
  ('Ireland', 'IE', 80),
  ('Israel', 'IL', 81),
  ('Italy', 'IT', 82),
  ('Ivory Coast', 'CI', 83),
  ('Jamaica', 'JM', 84),
  ('Japan', 'JP', 85),
  ('Jordan', 'JO', 86),
  ('Kazakhstan', 'KZ', 87),
  ('Kenya', 'KE', 88),
  ('Kiribati', 'KI', 89),
  ('Korea, North', 'KP', 90),
  ('Korea, South', 'KR', 91),
  ('Kuwait', 'KW', 92),
  ('Kyrgyzstan', 'KG', 93),
  ('Laos', 'LA', 94),
  ('Latvia', 'LV', 95),
  ('Lebanon', 'LB', 96),
  ('Lesotho', 'LS', 97),
  ('Liberia', 'LR', 98),
  ('Libya', 'LY', 99),
  ('Liechtenstein', 'LI', 100),
  ('Lithuania', 'LT', 101),
  ('Luxembourg', 'LU', 102),
  ('Madagascar', 'MG', 103),
  ('Malawi', 'MW', 104),
  ('Malaysia', 'MY', 105),
  ('Maldives', 'MV', 106),
  ('Mali', 'ML', 107),
  ('Malta', 'MT', 108),
  ('Marshall Islands', 'MH', 109),
  ('Mauritania', 'MR', 110),
  ('Mauritius', 'MU', 111),
  ('Mexico', 'MX', 112),
  ('Micronesia', 'FM', 113),
  ('Moldova', 'MD', 114),
  ('Monaco', 'MC', 115),
  ('Mongolia', 'MN', 116),
  ('Montenegro', 'ME', 117),
  ('Morocco', 'MA', 118),
  ('Mozambique', 'MZ', 119),
  ('Myanmar', 'MM', 120),
  ('Namibia', 'NA', 121),
  ('Nauru', 'NR', 122),
  ('Nepal', 'NP', 123),
  ('Netherlands', 'NL', 124),
  ('New Zealand', 'NZ', 125),
  ('Nicaragua', 'NI', 126),
  ('Niger', 'NE', 127),
  ('Nigeria', 'NG', 128),
  ('North Macedonia', 'MK', 129),
  ('Norway', 'NO', 130),
  ('Oman', 'OM', 131),
  ('Pakistan', 'PK', 132),
  ('Palau', 'PW', 133),
  ('Panama', 'PA', 134),
  ('Papua New Guinea', 'PG', 135),
  ('Paraguay', 'PY', 136),
  ('Peru', 'PE', 137),
  ('Philippines', 'PH', 138),
  ('Poland', 'PL', 139),
  ('Portugal', 'PT', 140),
  ('Qatar', 'QA', 141),
  ('Romania', 'RO', 142),
  ('Russia', 'RU', 143),
  ('Rwanda', 'RW', 144),
  ('Saint Kitts and Nevis', 'KN', 145),
  ('Saint Lucia', 'LC', 146),
  ('Saint Vincent and the Grenadines', 'VC', 147),
  ('Samoa', 'WS', 148),
  ('San Marino', 'SM', 149),
  ('Sao Tome and Principe', 'ST', 150),
  ('Saudi Arabia', 'SA', 151),
  ('Senegal', 'SN', 152),
  ('Serbia', 'RS', 153),
  ('Seychelles', 'SC', 154),
  ('Sierra Leone', 'SL', 155),
  ('Singapore', 'SG', 156),
  ('Slovakia', 'SK', 157),
  ('Slovenia', 'SI', 158),
  ('Solomon Islands', 'SB', 159),
  ('Somalia', 'SO', 160),
  ('South Africa', 'ZA', 161),
  ('South Sudan', 'SS', 162),
  ('Spain', 'ES', 163),
  ('Sri Lanka', 'LK', 164),
  ('Sudan', 'SD', 165),
  ('Suriname', 'SR', 166),
  ('Sweden', 'SE', 167),
  ('Switzerland', 'CH', 168),
  ('Syria', 'SY', 169),
  ('Tajikistan', 'TJ', 170),
  ('Tanzania', 'TZ', 171),
  ('Thailand', 'TH', 172),
  ('Timor-Leste', 'TL', 173),
  ('Togo', 'TG', 174),
  ('Tonga', 'TO', 175),
  ('Trinidad and Tobago', 'TT', 176),
  ('Tunisia', 'TN', 177),
  ('Turkey', 'TR', 178),
  ('Turkmenistan', 'TM', 179),
  ('Tuvalu', 'TV', 180),
  ('Uganda', 'UG', 181),
  ('Ukraine', 'UA', 182),
  ('United Arab Emirates', 'AE', 183),
  ('United Kingdom', 'GB', 184),
  ('United States', 'US', 185),
  ('Uruguay', 'UY', 186),
  ('Uzbekistan', 'UZ', 187),
  ('Vanuatu', 'VU', 188),
  ('Venezuela', 'VE', 189),
  ('Vietnam', 'VN', 190),
  ('Yemen', 'YE', 191),
  ('Zambia', 'ZM', 192),
  ('Zimbabwe', 'ZW', 193),
  ('Holy See', 'VA', 194),
  ('Palestine', 'PS', 195)
) as v(name, code, sort_order);
