-- All 63 US National Parks (NPS "National Park" designation), alphabetical.
-- code = kebab-case slug. metadata.state = USPS state abbreviation(s),
-- comma-separated for parks spanning more than one state.
with target_list as (
  select id from public.lists where slug = 'national-parks'
)
insert into public.list_items (list_id, name, code, sort_order, metadata)
select target_list.id, v.name, v.code, v.sort_order, v.metadata
from target_list, (values
  ('Acadia', 'acadia', 1, '{"state":"ME"}'::jsonb),
  ('American Samoa', 'american-samoa', 2, '{"state":"AS"}'::jsonb),
  ('Arches', 'arches', 3, '{"state":"UT"}'::jsonb),
  ('Badlands', 'badlands', 4, '{"state":"SD"}'::jsonb),
  ('Big Bend', 'big-bend', 5, '{"state":"TX"}'::jsonb),
  ('Biscayne', 'biscayne', 6, '{"state":"FL"}'::jsonb),
  ('Black Canyon of the Gunnison', 'black-canyon-of-the-gunnison', 7, '{"state":"CO"}'::jsonb),
  ('Bryce Canyon', 'bryce-canyon', 8, '{"state":"UT"}'::jsonb),
  ('Canyonlands', 'canyonlands', 9, '{"state":"UT"}'::jsonb),
  ('Capitol Reef', 'capitol-reef', 10, '{"state":"UT"}'::jsonb),
  ('Carlsbad Caverns', 'carlsbad-caverns', 11, '{"state":"NM"}'::jsonb),
  ('Channel Islands', 'channel-islands', 12, '{"state":"CA"}'::jsonb),
  ('Congaree', 'congaree', 13, '{"state":"SC"}'::jsonb),
  ('Crater Lake', 'crater-lake', 14, '{"state":"OR"}'::jsonb),
  ('Cuyahoga Valley', 'cuyahoga-valley', 15, '{"state":"OH"}'::jsonb),
  ('Death Valley', 'death-valley', 16, '{"state":"CA, NV"}'::jsonb),
  ('Denali', 'denali', 17, '{"state":"AK"}'::jsonb),
  ('Dry Tortugas', 'dry-tortugas', 18, '{"state":"FL"}'::jsonb),
  ('Everglades', 'everglades', 19, '{"state":"FL"}'::jsonb),
  ('Gates of the Arctic', 'gates-of-the-arctic', 20, '{"state":"AK"}'::jsonb),
  ('Gateway Arch', 'gateway-arch', 21, '{"state":"MO"}'::jsonb),
  ('Glacier', 'glacier', 22, '{"state":"MT"}'::jsonb),
  ('Glacier Bay', 'glacier-bay', 23, '{"state":"AK"}'::jsonb),
  ('Grand Canyon', 'grand-canyon', 24, '{"state":"AZ"}'::jsonb),
  ('Grand Teton', 'grand-teton', 25, '{"state":"WY"}'::jsonb),
  ('Great Basin', 'great-basin', 26, '{"state":"NV"}'::jsonb),
  ('Great Sand Dunes', 'great-sand-dunes', 27, '{"state":"CO"}'::jsonb),
  ('Great Smoky Mountains', 'great-smoky-mountains', 28, '{"state":"TN, NC"}'::jsonb),
  ('Guadalupe Mountains', 'guadalupe-mountains', 29, '{"state":"TX"}'::jsonb),
  ('Haleakala', 'haleakala', 30, '{"state":"HI"}'::jsonb),
  ('Hawaii Volcanoes', 'hawaii-volcanoes', 31, '{"state":"HI"}'::jsonb),
  ('Hot Springs', 'hot-springs', 32, '{"state":"AR"}'::jsonb),
  ('Indiana Dunes', 'indiana-dunes', 33, '{"state":"IN"}'::jsonb),
  ('Isle Royale', 'isle-royale', 34, '{"state":"MI"}'::jsonb),
  ('Joshua Tree', 'joshua-tree', 35, '{"state":"CA"}'::jsonb),
  ('Katmai', 'katmai', 36, '{"state":"AK"}'::jsonb),
  ('Kenai Fjords', 'kenai-fjords', 37, '{"state":"AK"}'::jsonb),
  ('Kings Canyon', 'kings-canyon', 38, '{"state":"CA"}'::jsonb),
  ('Kobuk Valley', 'kobuk-valley', 39, '{"state":"AK"}'::jsonb),
  ('Lake Clark', 'lake-clark', 40, '{"state":"AK"}'::jsonb),
  ('Lassen Volcanic', 'lassen-volcanic', 41, '{"state":"CA"}'::jsonb),
  ('Mammoth Cave', 'mammoth-cave', 42, '{"state":"KY"}'::jsonb),
  ('Mesa Verde', 'mesa-verde', 43, '{"state":"CO"}'::jsonb),
  ('Mount Rainier', 'mount-rainier', 44, '{"state":"WA"}'::jsonb),
  ('New River Gorge', 'new-river-gorge', 45, '{"state":"WV"}'::jsonb),
  ('North Cascades', 'north-cascades', 46, '{"state":"WA"}'::jsonb),
  ('Olympic', 'olympic', 47, '{"state":"WA"}'::jsonb),
  ('Petrified Forest', 'petrified-forest', 48, '{"state":"AZ"}'::jsonb),
  ('Pinnacles', 'pinnacles', 49, '{"state":"CA"}'::jsonb),
  ('Redwood', 'redwood', 50, '{"state":"CA"}'::jsonb),
  ('Rocky Mountain', 'rocky-mountain', 51, '{"state":"CO"}'::jsonb),
  ('Saguaro', 'saguaro', 52, '{"state":"AZ"}'::jsonb),
  ('Sequoia', 'sequoia', 53, '{"state":"CA"}'::jsonb),
  ('Shenandoah', 'shenandoah', 54, '{"state":"VA"}'::jsonb),
  ('Theodore Roosevelt', 'theodore-roosevelt', 55, '{"state":"ND"}'::jsonb),
  ('Virgin Islands', 'virgin-islands', 56, '{"state":"VI"}'::jsonb),
  ('Voyageurs', 'voyageurs', 57, '{"state":"MN"}'::jsonb),
  ('White Sands', 'white-sands', 58, '{"state":"NM"}'::jsonb),
  ('Wind Cave', 'wind-cave', 59, '{"state":"SD"}'::jsonb),
  ('Wrangell-St. Elias', 'wrangell-st-elias', 60, '{"state":"AK"}'::jsonb),
  ('Yellowstone', 'yellowstone', 61, '{"state":"WY, MT, ID"}'::jsonb),
  ('Yosemite', 'yosemite', 62, '{"state":"CA"}'::jsonb),
  ('Zion', 'zion', 63, '{"state":"UT"}'::jsonb)
) as v(name, code, sort_order, metadata);
